const AuthActionType = {
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAIL: 'LOGIN_FAIL',
	USER_LOGOUT: 'USER_LOGOUT'
}

const GetUserType = {
	GETUSER_SUCCESS: 'GETUSER_SUCCESS',
	GETUSER_FAIL: 'GETUSER_FAIL'
}

export {AuthActionType, GetUserType}