const AuthActionType = {
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAIL: 'LOGIN_FAIL',
	USER_LOGOUT: 'USER_LOGOUT'
}

const AuthWithRememberActionType = {
	LOGINWITHREMEMBER_SUCCESS: 'LOGINWITHREMEMBER_SUCCESS',
}

const UserActionType = {
	GETUSER_SUCCESS: 'GETUSER_SUCCESS',
	GETUSER_FAIL: 'GETUSER_FAIL',
	MODIFYUSER_SUCCESS: 'MODIFYUSER_SUCCESS',
	MODIFYUSER_FAIL: 'MODIFYUSER_FAIL'
}

export {AuthActionType, AuthWithRememberActionType, UserActionType}